apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsbird-deployment
  labels:
    app: newsbird
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newsbird
  template:
    metadata:
      labels:
        app: newsbird 
    spec:
      containers:
      - name: nodeserver
        image: narasimharao12/newsbird:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: newsbird 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000